default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000


development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: panda 
  username: postgres
  password: 12345
  host: localhost


test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: panda_test
  username: postgres
  password: 12345
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: dima1212_piona55
  username: dima1212_piona55
  password: tSmoE4Tpi
  host: postgresql7.locum.ru