default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5


development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: piona	
  username: postgres
  password: 12345
  host: localhost


